### ISSUE TITLE
No use of Continuity Cost and Torque Randomization in the scripts

### ISSUE THREAD

**Issue by arko206** [continual-dr/continual-dr#1]
I have gone through the grasper_env.py and reacher_env.py, although in these implementations continuity cost has been implemented and Torque Randomization has been initialized, but they were not used anywhere inside the code.

**Comment by josifovski** [comment]
**Torque randomization:** Unlike the latency and the noise randomization, which are implemented on the python side, the torque randomization is implemented at the simulator side. The simulator accepts a **-rt** (randomize torque) parameter, and to enable torque randomization you should pass a value of 1 for it. For example, this is done in line 50 of [simulator_vec_env.py](https://github.com/continual-dr/continual-dr/blob/main/scripts/simulator_vec_env.py) if you are starting the simulator as subprocess, so you only need to modify the config. 

If you are starting the simulator manually, you can start it from the command line with **./ManipulatorEnvironment.x86_64 -rt 1** to enable torque randomization. 

Regarding the implementation details, the torque is randomized by randomizing the stiffness and damping values within the ranges mentioned in the paper, and the implementation is based on the code provided in [unity robotics hub ](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/urdf_importer/urdf_appendix.md) using the Spring-Damper equation. 

**Continuity cost:** Regarding the continuity cost, it is only used as an evaluation metric for trained models. We have not pushed the scripts for creating the tables in the paper, but you can easily modify the evaluate_model.py script to show the continuity cost for a trained model. The logic is that each environment stores the history of executed actions from the last episode, so you can just add the line:
```print("cont_cost: {0}".format(np.mean(np.array([env.continuity_cost() for env in eval_env_ideal.envs]))))``` 

at the end of the script, after evaluate_model(model_path=args.model_path, env=eval_env_ideal) has been called. 

You can use the same function and logic from the reacher_environment for the grasper_environment, just for the grasper environment in our case you should use the first 200 actions, as the last 100 actions are hard-coded( 50 timesteps to close the gripper and 50 timesteps to lift the arm).
